os: linux

vm:
  size: [large]
language: java
cache: bundler
dist: bionic


install: skip

jobs:
  include:
      script: true
	  echo "$SECRET_KEY"

after_success:
  - echo done
  - echo $TRAVIS_TEST_RESULT
after_failure:
  - echo failed
  - echo $TRAVIS_TEST_RESULT
